"""Initial Migration

Revision ID: 5f3ea30d645d
Revises: 280c3e460d19
Create Date: 2019-12-02 18:49:02.495171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3ea30d645d'
down_revision = '280c3e460d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_column('posts', 'timestamp')
    op.drop_column('comments', 'time')
    # ### end Alembic commands ###
